# Generated by Django 5.1.2 on 2024-11-15 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booksdb_rating_rentalsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksdb',
            name='cover_book',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp'])]),
        ),
        migrations.AddField(
            model_name='library',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booksdb',
            name='isbn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booksdb',
            name='isbn13',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
